# Generated by Django 5.0.6 on 2024-05-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference', models.CharField(max_length=100)),
                ('Vetement', models.CharField(max_length=100)),
                ('Couleur', models.CharField(max_length=100)),
                ('Taille', models.CharField(max_length=10)),
                ('Quantite', models.IntegerField()),
                ('Prix_unitaire', models.FloatField()),
                ('Prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
