# Generated by Django 5.0.6 on 2024-05-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet03', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('reference', models.TextField(primary_key=True, serialize=False)),
                ('vetement', models.TextField()),
                ('couleur', models.TextField()),
                ('taille', models.TextField()),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.FloatField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'stock_magasin',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='StockMagasin',
        ),
    ]
